import AvatarI from "../../img/avatar.png";
import Cheff1I from "../../img/chef1.png";
import CheffI from "../../img/cheff.png";
import LogoI from "../../img/chef1.png";
import HmI from "../../img/hm1.png";
import me1 from "../../img/caesar-salad.jpg";
import me2 from "../../img/mac-and-cheese.jpg";
import me3 from "../../img/chicken-curry.jpg";
import authImg from "../../img/auth-img.png";
import BikeDeliveryI from "../../img/delivery.png";
import HeroBgI from "../../img/hero-bg.png";
import EmptyCartI from "../../img/emptyCart.svg";
import NotFoundI from "../../img/NotFound.svg";
import Visa from "../../img/visa.png";
import Momo from "../../img/momo.png";
import IcreamI from "../../img/i1.png";
import StrawberryI from "../../img/f5.png";
import ChickenI from "../../img/c3.png";
import FishI from "../../img/fi3.png";

export const Logo = LogoI;
export const Hm = HmI;
export const AuthImg = authImg;
export const Avatar = AvatarI;
export const Cheff = CheffI;
export const Cheff1 = Cheff1I;
export const BikeDelivery = BikeDeliveryI;
export const HeroBg = HeroBgI;
export const Icecream = IcreamI;
export const Strawberry = StrawberryI;
export const Chicken = ChickenI;
export const Fish = FishI;
export const Meal1 = me1;
export const Meal2 = me2;
export const Meal3 = me3;
export const EmptyCartImg = EmptyCartI;
export const NotFoundImg = NotFoundI;
export const CreditCard = Visa;
export const MOMO = Momo;
